// Generated from the Obsidian project archive. Do not edit manually.
export const projects = [
  {
    "slug": "anarqueologias",
    "category": "Colaboraciones",
    "titleEs": "Anarqueologías",
    "titleEn": "Anarchaeologies",
    "period": "noviembre de 2025-febrero de 2026",
    "year": 2026,
    "status": "terminado",
    "type": "colaboración / intervención cerámica",
    "place": "El Imparcial, C. Duque de Alba 4, Madrid",
    "exhibition": "Anarqueologías",
    "institution": "El Imparcial",
    "curator": "PENDIENTE",
    "collaborators": "El Imparcial; texto de sala de Gisela Novais",
    "introEs": "Una arqueología sin origen cierto intervino la mesa de El Imparcial con reliquias, ruinas y pruebas cerámicas sometidos a una transformación continua.",
    "introEn": "An archaeology with no certain origin intervened in El Imparcial's table through ceramic relics, ruins and germs in continuous transformation.",
    "bodyEs": "Anarqueologías* intervino la mesa de la antesala de El Imparcial con una ficción material que podía tocarse, mirarse y recorrerse desde distintos ángulos. Las piezas aparecían como restos de una civilización imaginada o fragmentos enviados desde un futuro incierto: algunas se afirmaban como reliquias; otras se ablandaban y conservaban la memoria del agua.\n\nLa serie mezcla arcillas recolectadas, metales reciclados, piedras y esmaltes experimentales. Brenda Ranieri no excava para fijar lo que fue, sino para escuchar lo que la materia todavía puede llegar a ser. El horno, el fuego y la incertidumbre participan en la construcción de cada forma. Instalada sobre una mesa destinada habitualmente al encuentro, la obra convirtió el espacio en un paisaje compartido y mutable.",
    "bodyEn": "Anarchaeologies* intervened in the antechamber table at El Imparcial with a material fiction that could be touched, observed and approached from different angles. The works appeared as remains of an imagined civilisation or fragments sent from an uncertain future: some asserted themselves as relics, while others seemed to soften, retaining the memory of water.\n\nThe series combines gathered clays, recycled metals, stones and experimental glazes. Brenda Ranieri does not excavate to fix what once was, but to listen to what matter may still become. The kiln, fire and uncertainty all participate in shaping each form. Installed on a table normally intended for gathering, the work transformed the space into a shared, mutable landscape.",
    "materials": "arcillas recolectadas, pastas refractarias, porcelana, metal reciclado, piedras naturales y esmaltes",
    "techniques": "modelado, mezcla de pastas, cocción experimental, ensamblaje e instalación",
    "dimensions": "instalación variable",
    "imageCount": 3,
    "number": 1
  },
  {
    "slug": "carabanchel-disena",
    "category": "Festivales",
    "titleEs": "Carabanchel Diseña",
    "titleEn": "Carabanchel Designs",
    "period": "marzo de 2026",
    "year": 2026,
    "status": "terminado",
    "type": "festival / exposición colectiva",
    "place": "C. Hermanos del Moral 34, Carabanchel, Madrid",
    "exhibition": "Carabanchel Diseña, Madrid Design Festival 2026",
    "institution": "Madrid Design Festival / Carabanchel Diseña",
    "curator": "PENDIENTE",
    "collaborators": "doce estudios de Carabanchel",
    "introEs": "Una muestra colectiva reunió por primera vez a doce estudios para presentar el diseño de Carabanchel como práctica colaborativa, experimental y arraigada en el territorio.",
    "introEn": "A group exhibition brought twelve studios together for the first time, presenting design in Carabanchel as a collaborative, experimental practice rooted in place.",
    "bodyEs": "Carabanchel Diseña* reunió prácticas de arte, diseño y oficios contemporáneos nacidas del hacer cotidiano, el cruce entre disciplinas y el arraigo territorial. La exposición presentó la identidad compartida de un ecosistema creativo que ha crecido desde la colaboración, la experimentación y la investigación material.\n\nBrenda Ranieri participó a través de Fresca. La nave, su estudio de creación contemporánea en Carabanchel. Su aportación situó la cerámica como práctica de investigación matérica y territorial, conectando procesos artesanales, recursos locales y pensamiento crítico. Dentro del conjunto, su trabajo contribuyó a una lectura del diseño como herramienta para construir futuro desde lo local.",
    "bodyEn": "Carabanchel Designs* brought together contemporary art, design and craft practices rooted in everyday making, interdisciplinary exchange and a strong connection to place. The exhibition presented the shared identity of a creative ecosystem that has grown through collaboration, experimentation and material research.\n\nBrenda Ranieri participated through Fresca. La nave, her contemporary creation studio in Carabanchel. Her contribution positioned ceramics as a practice of material and territorial research, connecting craft processes, local resources and critical thought. Within the collective presentation, her work contributed to an understanding of design as a tool for building the future from the local level.",
    "materials": "cerámica y materiales de investigación del estudio",
    "techniques": "práctica cerámica experimental e instalación",
    "dimensions": "PENDIENTE",
    "imageCount": 3,
    "number": 2
  },
  {
    "slug": "cosas-que-cargan-cosas",
    "category": "Exposiciones colectivas",
    "titleEs": "Cosas que cargan cosas",
    "titleEn": "Things That Carry Things",
    "period": "25 de abril-30 de mayo de 2026",
    "year": 2026,
    "status": "terminado",
    "type": "exposición colectiva",
    "place": "Doble Erre, Nicolás Sánchez 109, Usera, Madrid",
    "exhibition": "Cosas que cargan cosas",
    "institution": "Ventana Project / Doble Erre",
    "curator": "Aquiles Jarrín y Eladio Aguilera",
    "collaborators": "artistas participantes de la exposición",
    "introEs": "Una exposición sobre recipientes, soportes y estructuras de cuidado en la que Brenda Ranieri presentó *Lo atamos con alambre* y *Antes del rayo*.",
    "introEn": "An exhibition about vessels, supports and structures of care in which Brenda Ranieri presented *We Tie It with Wire* and *Before the Lightning*.",
    "bodyEs": "Inspirada en *La teoría de la bolsa de la ficción* de Ursula K. Le Guin, *Cosas que cargan cosas* desplaza el relato del arma al recipiente: la bolsa, la cesta, el saco y la vasija como tecnologías fundamentales para sostener, almacenar y hacer durar. La muestra actualiza estas formas más allá de su función primaria y atiende también a las peanas, sujeciones y apoyos que acompañan a la obra.\n\nBrenda Ranieri participó con *Lo atamos con alambre*, una fuente construida con cerámica, hormigón, agua, metales y plástico reciclado. El ensamblaje propone un equilibrio precario en el que sostener implica también ser sostenido. Su título recupera una expresión argentina asociada a resolver con ingenio y urgencia a partir de lo disponible. También presentó *Antes del rayo*, una pieza de porcelana y metal donde fragilidad y tensión permanecen contenidas en una escala íntima.",
    "bodyEn": "Inspired by Ursula K. Le Guin's *The Carrier Bag Theory of Fiction*, *Things That Carry Things* shifts the narrative from the weapon to the container: the bag, basket, sack and vessel as fundamental technologies for holding, storing and making things last. The exhibition updates these forms beyond their primary function and also attends to the plinths and supports that accompany the artwork.\n\nBrenda Ranieri participated with *We Tie It with Wire*, a fountain built from ceramics, concrete, water, metals and recycled plastic. The assembly proposes a precarious balance in which holding also means being held. Its title borrows an Argentine expression for solving a difficulty with ingenuity, urgency and whatever is available. She also presented *Before the Lightning*, a porcelain and metal work in which fragility and tension remain contained on an intimate scale.",
    "materials": "cerámica, porcelana, hormigón, agua, distintos metales y plástico reciclado",
    "techniques": "construcción cerámica, ensamblaje, instalación hidráulica y técnica mixta",
    "dimensions": "Lo atamos con alambre*, 70 × 75 cm de diámetro; *Antes del rayo*, 20 × 16 cm",
    "imageCount": 3,
    "number": 3
  },
  {
    "slug": "la-forma-del-agua-quieta",
    "category": "Exposiciones individuales",
    "titleEs": "La forma del agua quieta",
    "titleEn": "The Shape of Still Water",
    "period": "junio-septiembre de 2026",
    "year": 2026,
    "status": "terminado",
    "type": "exposición individual / instalación escultórica",
    "place": "Madrid",
    "exhibition": "La forma del agua quieta",
    "institution": "Galería Lapislázuli, patios de Garaje Vistahermosa",
    "curator": "PENDIENTE",
    "collaborators": "Galería Lapislázuli; Garaje Vistahermosa",
    "introEs": "Una serie de fuentes cerámicas convierte los patios de la galería en hidrografías de lo menor, donde agua, arcilla y tiempo permanecen activos incluso cuando el movimiento parece detenido.",
    "introEn": "A series of ceramic fountains transforms the gallery courtyards into minor hydrographies, where water, clay and time remain active even when movement appears to have stopped.",
    "bodyEs": "La forma del agua quieta* parte de la relación entre jardín, fuente y cerámica como dispositivos para contener y dar cuerpo a materias inestables. Vasijas realizadas con arcillas locales y rocas recolectadas en el territorio conforman una serie de instalaciones de agua que intervienen los patios de la galería.\n\nLa propuesta nace de una contradicción: aquello que percibimos como inmóvil está atravesado por procesos continuos de transformación. El agua nunca permanece quieta; sedimenta, evapora, erosiona y circula incluso cuando parece detenida. Frente a la imagen apaciguada del jardín ornamental, la exposición revela ritmos lentos y casi imperceptibles, compartidos por el agua y la práctica cerámica.\n\nEntre ruinas, azulejos y vasijas, las fuentes funcionan como cuerpos en cambio permanente. Arcilla, piedra, porcelana, metal y esmalte conservan las marcas del fuego y del territorio, mientras el agua reactiva las piezas y las mantiene abiertas al tiempo.",
    "bodyEn": "The Shape of Still Water* begins with the relationship between garden, fountain and ceramics as devices that contain and give form to unstable matter. Vessels made from local clays and rocks gathered from the surrounding territory form a series of water installations throughout the gallery courtyards.\n\nThe proposal grows from a contradiction: what we perceive as still is traversed by continuous processes of transformation. Water never truly remains motionless; it sediments, evaporates, erodes and circulates even when it seems at rest. Against the pacified image of the ornamental garden, the exhibition reveals slow, nearly imperceptible rhythms shared by water and ceramic practice.\n\nAmong ruins, tiles and vessels, the fountains operate as bodies in permanent change. Clay, stone, porcelain, metal and glaze retain the traces of fire and territory, while water reactivates the works and keeps them open to time.",
    "materials": "porcelana, pasta refractaria, arcilla local recolectada, piedras naturales, esmalte, metal y agua",
    "techniques": "modelado y construcción cerámica, formulación de esmaltes, cocción de alta temperatura, ensamblaje e instalación hidráulica",
    "dimensions": "conjunto variable; piezas documentadas de 105 × 90 cm y 71 × 40 cm",
    "imageCount": 3,
    "number": 4
  },
  {
    "slug": "oax-car-38-57",
    "category": "Bienal",
    "titleEs": "OAX-CAR-38-57",
    "titleEn": "OAX-CAR-38-57",
    "period": "2025-2026",
    "year": 2026,
    "status": "en curso",
    "type": "investigación / instalación / archivo material",
    "place": "Oaxaca, Carabanchel y el Atlántico Norte",
    "exhibition": "Iberoamérica y Carabanchel: diálogos desde el diseño, BID 2026",
    "institution": "DIMAD / Bienal Iberoamericana de Diseño; Central de Diseño, Matadero Madrid y estudios de Carabanchel",
    "curator": "DIMAD / BID",
    "collaborators": "Fresca. La nave y estudios participantes",
    "introEs": "Un archivo material y especulativo conecta Oaxaca y Carabanchel a través del agua, las arcillas locales, el Códice de Madrid y la búsqueda cerámica de un punto eutéctico.",
    "introEn": "A material and speculative archive connects Oaxaca and Carabanchel through water, local clays, the Madrid Codex and the ceramic search for a eutectic point.",
    "bodyEs": "OAX-CAR-38-57* responde de forma crítica y contemporánea a *Cartografías de la Artesanía del Estado de Oaxaca* (2013), una plataforma digital hoy desaparecida. Ante la ausencia de un archivo tangible, el proyecto propone crear uno nuevo: no como reconstrucción, sino como gesto situado y especulativo que pone en relación dos territorios radicalmente distintos.\n\nEl código del título alude a Oaxaca, Carabanchel y a las coordenadas de un punto equidistante entre ambos, situado en el Atlántico Norte. El agua funciona como espacio simbólico de encuentro y como eje de una investigación sobre el eutéctico: el punto exacto en que materiales con temperaturas de fusión diferentes se ablandan juntos. Esa imagen permite pensar el vínculo no como síntesis, sino como umbral de transformación mutua.\n\nLa investigación combina arcilla silvestre de Carabanchel, hojas de magnolio y ficus calcinadas para esmaltes, residuos de los demás estudios participantes y fotografías analógicas tomadas en Oaxaca en 2015. El Códice Tro-Cortesiano o Códice de Madrid, en especial la iconografía del dios de la lluvia Chaac, activa el plano simbólico. Ruinas, reliquias, pruebas de material y documentos forman un archivo abierto sobre memoria, migración y territorio.",
    "bodyEn": "OAX-CAR-38-57* offers a critical, contemporary response to *Cartographies of Craft in the State of Oaxaca* (2013), a now-defunct digital platform. Faced with the absence of a tangible archive, the project proposes a new one: not as reconstruction, but as a situated and speculative gesture that brings two radically different territories into relation.\n\nThe title's code refers to Oaxaca, Carabanchel and the coordinates of an equidistant point between them in the North Atlantic. Water operates as a symbolic meeting place and as the axis of research into the eutectic: the exact point at which materials with different melting temperatures soften together. This image makes it possible to understand connection not as synthesis, but as a threshold of mutual transformation.\n\nThe research combines wild clay from Carabanchel, magnolia and ficus leaves calcined for glazes, waste from the other participating studios and analogue photographs taken in Oaxaca in 2015. The Tro-Cortesianus or Madrid Codex, especially the iconography of the rain god Chaac, activates the symbolic dimension. Ruins, relics, material tests and documents form an open archive about memory, migration and territory.",
    "materials": "arcilla silvestre de Carabanchel, cerámica, esmaltes de ceniza de magnolio y ficus, metal, madera, residuos de estudios participantes y fotografía analógica",
    "techniques": "recolección, formulación y pruebas lineales de esmaltes, cocción, ensamblaje, archivo y deriva territorial",
    "dimensions": "instalación variable",
    "imageCount": 3,
    "number": 5
  },
  {
    "slug": "ruta-off-cerartmic-escala-house",
    "category": "Colaboraciones",
    "titleEs": "Ruta OFF cerARTmic - Escala House",
    "titleEn": "OFF cerARTmic Route - Escala House",
    "period": "20 de mayo-7 de junio de 2026",
    "year": 2026,
    "status": "terminado",
    "type": "colaboración / ruta expositiva",
    "place": "Escala House, Madrid",
    "exhibition": "OFF cerARTmic 2026",
    "institution": "cerARTmic / Escala House",
    "curator": "cerARTmic",
    "collaborators": "Escala House y espacios participantes de la ruta",
    "introEs": "La ruta OFF cerARTmic insertó cerámica contemporánea en espacios cotidianos de Madrid; Brenda Ranieri presentó su trabajo en Escala House.",
    "introEn": "The OFF cerARTmic route inserted contemporary ceramics into everyday spaces across Madrid; Brenda Ranieri presented her work at Escala House.",
    "bodyEs": "OFF cerARTmic es una ruta expositiva que desplaza la cerámica contemporánea fuera de la feria y la integra en boutiques y espacios de Madrid. La iniciativa acerca las obras a nuevos públicos y propone otros modos de relación entre pieza, arquitectura y contexto cotidiano.\n\nBrenda Ranieri participó en Escala House con una selección vinculada a su investigación sobre las relaciones entre cuerpo, territorio y memoria. Su práctica parte de arcillas locales que recolecta y transforma en pastas cerámicas propias, incorporando también metales reciclados, restos urbanos y elementos naturales. Mediante esmaltes experimentales y procesos de cocción abiertos a la incertidumbre, cada pieza se construye como un diálogo entre intención y comportamiento material. Su trabajo se sitúa así entre lo geológico, lo arqueológico y lo afectivo, y entiende la cerámica como una forma de lectura sensible del entorno.",
    "bodyEn": "OFF cerARTmic is an exhibition route that moves contemporary ceramics beyond the fair and integrates it into boutiques and spaces throughout Madrid. The initiative brings artworks to new audiences and proposes other relationships among object, architecture and everyday context.\n\nBrenda Ranieri participated at Escala House with a selection connected to her research into the relationships among body, territory and memory. Her practice begins with local clays that she gathers and transforms into her own ceramic bodies, also incorporating recycled metals, urban remnants and natural elements. Through experimental glazes and firing processes that remain open to uncertainty, each work emerges from a dialogue between intention and material behaviour. Her practice is situated between the geological, the archaeological and the affective, understanding ceramics as a sensitive way of reading the environment.",
    "materials": "arcillas locales, pastas cerámicas propias, metales reciclados, restos urbanos, elementos naturales y esmaltes experimentales",
    "techniques": "recolección, formulación de pastas y esmaltes, modelado, cocción experimental e instalación",
    "dimensions": "variables",
    "imageCount": 3,
    "number": 6
  },
  {
    "slug": "ohm-2025-anarqueologias",
    "category": "Festivales",
    "titleEs": "Anarqueologías",
    "titleEn": "Anarchaeologies",
    "period": "26-27 de septiembre de 2025",
    "year": 2025,
    "status": "terminado",
    "type": "festival / open studio / instalación",
    "place": "Carabanchel, Madrid",
    "exhibition": "Open House Madrid 2025",
    "institution": "Fresca. La nave",
    "curator": "PENDIENTE",
    "collaborators": "Open House Madrid",
    "introEs": "Un estudio abierto convertido en arqueología imaginada, donde vasijas, ruinas, germinaciones y una fuente revelan la memoria mutable de la materia.",
    "introEn": "An open studio transformed into an imagined archaeology, where vessels, ruins, germinations and a fountain reveal matter's mutable memory.",
    "bodyEs": "En el marco de Open House Madrid 2025, Brenda Ranieri abrió su espacio de trabajo como un territorio donde lo sólido y lo inacabado conviven. Las formas cerámicas aparecían como vestigios de una arqueología imaginada: piezas procedentes de un tiempo incierto, a medio camino entre ruina y germen.\n\nCada obra surge de la mezcla de pastas cerámicas con arcilla local, metal reciclado y otros recursos naturales. Al atravesar distintas temperaturas, estos materiales se expanden, resisten o se deforman, convirtiendo al horno en coautor. Una fuente situada en el centro de la instalación mantuvo vivo el diálogo entre fuego, agua y tierra. La propuesta invitaba a percibir aquello que permanece y aquello que está a punto de mutar.",
    "bodyEn": "Within Open House Madrid 2025, Brenda Ranieri opened her workspace as a territory where the solid and the unfinished coexist. Ceramic forms appeared as remains of an imagined archaeology: works from an uncertain time, halfway between ruin and germination.\n\nEach work emerges from mixtures of ceramic bodies with local clay, recycled metal and other natural resources. Exposed to different temperatures, these materials expand, resist or deform, turning the kiln into a co-author. A fountain at the centre of the installation kept the dialogue between fire, water and earth alive. The project invited visitors to perceive both what remains and what is about to change.",
    "materials": "pastas refractarias, porcelana, arcilla local, metal reciclado, esmaltes, piedras naturales y agua",
    "techniques": "modelado, mezcla de pastas, cocción experimental, ensamblaje e instalación hidráulica",
    "dimensions": "instalación variable",
    "imageCount": 3,
    "number": 7
  },
  {
    "slug": "bioceramica-a-base-de-residuos-de-cafe",
    "category": "Residencias",
    "titleEs": "Biocerámica a base de residuos de café",
    "titleEn": "Coffee-Waste Bioceramics",
    "period": "13 de noviembre-finales de diciembre de 2025",
    "year": 2025,
    "status": "terminado",
    "type": "residencia / investigación material",
    "place": "Escala House, Madrid",
    "exhibition": "residencia artística de Brenda Ranieri",
    "institution": "Escala House",
    "curator": "PENDIENTE",
    "collaborators": "Escala House",
    "introEs": "Una residencia de investigación exploró los residuos de café como materia para desafiar la idea de permanencia asociada a la cerámica.",
    "introEn": "A research residency explored coffee waste as a material through which to challenge the permanence traditionally associated with ceramics.",
    "bodyEs": "Durante su residencia en Escala House, Brenda Ranieri desarrolló una investigación sobre biocerámica a base de residuos de café. El proyecto extendió su práctica situada, habitualmente construida con arcillas locales, metales reciclados y recursos naturales, hacia un residuo cotidiano generado por la propia casa.\n\nLa investigación entendió el taller como un espacio de observación donde la materia conserva y revela información. Al incorporar café a pruebas, mezclas y cuerpos cerámicos, el proyecto atendió a sus transformaciones durante el secado y la cocción y a las huellas que deja al desaparecer o integrarse. La cerámica aparece así como una forma de desafiar lo perenne: un campo en el que control e incertidumbre, materia geológica y residuo orgánico negocian una forma común.",
    "bodyEn": "During her residency at Escala House, Brenda Ranieri developed research into bioceramics made with coffee waste. The project extended her situated practice—usually built from local clays, recycled metals and natural resources—towards an everyday residue generated by the house itself.\n\nThe research understood the studio as a space of observation in which matter retains and reveals information. By incorporating coffee into tests, mixtures and ceramic bodies, the project attended to its transformations during drying and firing and to the traces it leaves as it disappears or becomes integrated. Ceramics thus becomes a way of challenging permanence: a field in which control and uncertainty, geological matter and organic waste negotiate a shared form.",
    "materials": "residuos de café, arcillas y pastas cerámicas, esmaltes experimentales",
    "techniques": "formulación de mezclas, pruebas de material, modelado, secado y cocción",
    "dimensions": "investigación y muestras de dimensiones variables",
    "imageCount": 3,
    "number": 8
  },
  {
    "slug": "certezas",
    "category": "Colaboraciones",
    "titleEs": "Certezas",
    "titleEn": "Certainties",
    "period": "enero de 2024-marzo de 2025",
    "year": 2025,
    "status": "terminado",
    "type": "colaboración / proyecto expositivo",
    "place": "El Imparcial, Madrid",
    "exhibition": "Certezas",
    "institution": "El Imparcial",
    "curator": "PENDIENTE",
    "collaborators": "El Imparcial",
    "introEs": "Grabado, pintura, serigrafía y cerámica organizan un archivo familiar donde memoria, invención y migración vuelven inestable la idea de certeza.",
    "introEn": "Printmaking, painting, screen printing and ceramics organise a family archive in which memory, invention and migration destabilise the idea of certainty.",
    "bodyEs": "Certezas* parte de las historias de una familia cuya raíz trasciende el suelo que habita: un folclore ecléctico español, italiano y argentino compuesto por símbolos, anécdotas, personajes y recuerdos. Con el tiempo, la repetición abre una falla entre certeza y verdad. Las partes ausentes de cada relato son completadas por la imaginación y por la licencia creativa de quien vuelve a contarlo.\n\nEl proyecto reunió grabado, pintura, serigrafía y cerámica en la escalera de El Imparcial. El recorrido obligaba a descubrir las piezas desde distintas alturas y a gestionar la inestabilidad de los peldaños. Esa falta de suelo firme reflejaba la experiencia de una raíz que se desplaza: vínculos que van, vienen y permanecen, y la paradójica ventaja de no pertenecer del todo.",
    "bodyEn": "Certainties* begins with the stories of a family whose roots extend beyond the ground it inhabits: an eclectic Spanish, Italian and Argentine folklore made of symbols, anecdotes, characters and memories. Over time, repetition opens a fault line between certainty and truth. The missing parts of each story are completed by imagination and by the creative licence of whoever tells it again.\n\nThe project brought together printmaking, painting, screen printing and ceramics along the staircase of El Imparcial. The route required visitors to discover the works from different heights and negotiate the instability of the steps. This lack of firm ground reflected the experience of roots in motion: bonds that leave, return and remain, and the paradoxical advantage of never fully belonging.",
    "materials": "papel, tinta, óleo, cerámica y esmaltes",
    "techniques": "monotipo, serigrafía, pintura, modelado cerámico e instalación",
    "dimensions": "variables",
    "imageCount": 3,
    "number": 9
  },
  {
    "slug": "hangar",
    "category": "Exposiciones colectivas",
    "titleEs": "Hangar",
    "titleEn": "Hangar",
    "period": "4 de octubre-4 de diciembre de 2025",
    "year": 2025,
    "status": "terminado",
    "type": "exposición colectiva",
    "place": "antiguo enclave portuario, Puerto de Estepona, Málaga",
    "exhibition": "Hangar",
    "institution": "Artelier 21, Av. Luis Braille 21",
    "curator": "Red House Art / Adolfo Sánchez",
    "collaborators": "artistas participantes de la exposición",
    "introEs": "En un espacio de memoria industrial, *Flores de hierro* confronta la dureza del metal con la fragilidad y capacidad de transformación de la cerámica.",
    "introEn": "In a space shaped by industrial memory, *Iron Flowers* confronts the hardness of metal with the fragility and transformative capacity of ceramics.",
    "bodyEs": "Hangar* reunió a nueve artistas de distintas generaciones en Artelier 21, un antiguo enclave portuario de Estepona transformado en laboratorio expositivo. Pintura, cerámica contemporánea, arte lumínico, abstracción y figuración convivieron en una propuesta que activó la memoria industrial del lugar y favoreció el intercambio entre prácticas emergentes y consolidadas.\n\nBrenda Ranieri presentó *Flores de hierro*, una serie de vasijas de pasta refractaria, metal y esmaltes de formulación propia. Las obras traducen la tensión entre dureza y fragilidad mediante la imagen paradójica del hierro que florece. Su densidad material y la poética del forjado introducen la tradición artesanal dentro de un discurso contemporáneo ligado a la historia productiva del espacio.",
    "bodyEn": "Hangar* brought together nine artists from different generations at Artelier 21, a former port site in Estepona transformed into an exhibition laboratory. Painting, contemporary ceramics, light art, abstraction and figuration coexisted in a project that activated the site's industrial memory and encouraged exchange between emerging and established practices.\n\nBrenda Ranieri presented *Iron Flowers*, a series of refractory-clay vessels incorporating metal and self-formulated glazes. The works translate the tension between hardness and fragility through the paradoxical image of iron in bloom. Their material density and poetics of forging bring craft tradition into a contemporary discourse tied to the productive history of the space.",
    "materials": "pasta refractaria, metal y esmaltes de formulación propia",
    "techniques": "modelado, ensamblaje con metal, formulación de esmaltes y cocción",
    "dimensions": "variables",
    "imageCount": 3,
    "number": 10
  },
  {
    "slug": "lo-velado",
    "category": "Festivales",
    "titleEs": "Lo velado",
    "titleEn": "The Veiled",
    "period": "febrero-marzo de 2025",
    "year": 2025,
    "status": "terminado",
    "type": "festival / exposición / open studio",
    "place": "Carabanchel, Madrid",
    "exhibition": "Lo velado, Open Studios Carabanchel / Madrid Design Festival 2025",
    "institution": "Fresca. La nave; Madrid Design Festival",
    "curator": "Alejandra Díaz-Guerra",
    "collaborators": "Carabanchel Distrito Cultural",
    "introEs": "Una ensoñación material convierte el estudio en jardín latente, entre ruina, agua y formas que transitan el umbral de lo visible.",
    "introEn": "A material reverie transforms the studio into a latent garden, among ruins, water and forms that cross the threshold of the visible.",
    "bodyEs": "Madrid Design Festival 2025, bajo el lema *Rediseñar el mundo*, reunió exposiciones, actividades y espacios OFF para mostrar el diseño como herramienta de transformación social y ambiental. Dentro de sus Open Studios de Carabanchel, *Lo velado* presentó el trabajo de Brenda Ranieri en Fresca. La nave.\n\nComisariada por Alejandra Díaz-Guerra, la exposición proponía una ensoñación como vibración capaz de unir, modelar y contener cuerpos. Cerámicas, agua y una atmósfera de jardín latente conducían al visitante por el umbral donde lo tangible se disuelve y lo invisible se revela. Las ruinas no aparecían como final, sino como origen de nuevas formas, memorias y posibilidades materiales.",
    "bodyEn": "Madrid Design Festival 2025, under the theme *Redesigning the World*, brought together exhibitions, activities and OFF spaces to present design as a tool for social and environmental transformation. Within its Carabanchel Open Studios, *The Veiled* presented Brenda Ranieri's work at Fresca. La nave.\n\nCurated by Alejandra Díaz-Guerra, the exhibition proposed reverie as a vibration capable of joining, shaping and containing bodies. Ceramics, water and the atmosphere of a latent garden led visitors through a threshold where the tangible dissolves and the invisible is revealed. Ruins appeared not as an ending but as the origin of new forms, memories and material possibilities.",
    "materials": "cerámica, esmaltes, metal, piedra y agua",
    "techniques": "modelado, cocción, ensamblaje e instalación",
    "dimensions": "instalación variable",
    "imageCount": 3,
    "number": 11
  },
  {
    "slug": "memorias-de-agua-y-barro",
    "category": "Festivales",
    "titleEs": "Memorias de agua y barro",
    "titleEn": "Memories of Water and Clay",
    "period": "3-4 de octubre de 2025",
    "year": 2025,
    "status": "terminado",
    "type": "festival / coloquio / taller",
    "place": "Carabanchel, Madrid",
    "exhibition": "Festival Cultural CRUZA Carabanchel 2025",
    "institution": "Fresca. La nave / Espacio ISO; Carabanchel Distrito Cultural",
    "curator": "PENDIENTE",
    "collaborators": "Romina Casile; Fresco.arte; Ayuntamiento de Madrid",
    "introEs": "Un coloquio y un taller experimental exploraron el agua como memoria territorial y la arcilla local como materia capaz de escuchar y conservar huellas.",
    "introEn": "A talk and an experimental workshop explored water as territorial memory and local clay as matter capable of listening and retaining traces.",
    "bodyEs": "CRUZA Carabanchel es un festival organizado por la comunidad de Carabanchel Distrito Cultural para acercar el arte al vecindario y fortalecer las redes creativas del distrito. En su edición de 2025, *Memorias de agua y barro* abrió un espacio para conversar y crear en torno a la cerámica contemporánea como medio de investigación poética y territorial.\n\nBrenda Ranieri participó en un coloquio con la artista e investigadora Romina Casile sobre poéticas del agua y procesos de creación con arcilla. Al día siguiente condujo un taller de cerámica experimental en el que el público realizó piezas con materiales naturales recolectados por la artista. Ambas actividades conectaron la escucha del paisaje con una práctica manual, colectiva y situada.",
    "bodyEn": "CRUZA Carabanchel is a festival organised by the Carabanchel Distrito Cultural community to bring art closer to local residents and strengthen the district's creative networks. In its 2025 edition, *Memories of Water and Clay* opened a space for conversation and making around contemporary ceramics as a means of poetic and territorial research.\n\nBrenda Ranieri joined artist and researcher Romina Casile for a conversation on the poetics of water and processes of creating with clay. The following day she led an experimental ceramics workshop in which participants made works with natural materials gathered by the artist. Both activities connected attentive listening to the landscape with a manual, collective and situated practice.",
    "materials": "arcilla y materiales naturales recolectados",
    "techniques": "coloquio, mediación, modelado y experimentación cerámica",
    "dimensions": "no aplica",
    "imageCount": 3,
    "number": 12
  },
  {
    "slug": "sin-embargo-se-mueve",
    "category": "Colaboraciones",
    "titleEs": "Sin embargo, se mueve",
    "titleEn": "And Yet It Moves",
    "period": "diciembre de 2025",
    "year": 2025,
    "status": "terminado",
    "type": "colaboración / cena inmersiva / instalación",
    "place": "Escala House, Madrid",
    "exhibition": "cena inmersiva Sin embargo, se mueve",
    "institution": "Escala House",
    "curator": "PENDIENTE",
    "collaborators": "equipo gastronómico de Escala House",
    "introEs": "Una cena inmersiva convirtió la mesa en un paisaje lunar donde lo comestible, lo pétreo y los fragmentos del taller compartieron un mismo territorio.",
    "introEn": "An immersive dinner transformed the table into a lunar landscape where the edible, the stony and fragments from the studio shared the same territory.",
    "bodyEs": "Entre lo lunar y lo terrestre, *Sin embargo, se mueve* propuso un gesto de comunión entre materia, cuerpo y entorno. Inspirada en la frase atribuida a Galileo, la experiencia atendía a los procesos invisibles de transformación que sostienen todo lo vivo: aquello que parece quieto continúa moviéndose.\n\nLa mesa se convirtió en territorio y paisaje material. Piezas cerámicas, piedras, metales y fragmentos reales del taller convivieron con un menú vegetal cuyas formas confundían lo comestible con lo rocoso: panes como piedras, bocados lunares, espumas, setas y un postre volcánico. La cerámica extendió así su investigación más allá del objeto, activándose mediante el tacto, la comida y la conversación colectiva.",
    "bodyEn": "Between the lunar and the terrestrial, *And Yet It Moves* proposed a gesture of communion among matter, body and environment. Inspired by the phrase attributed to Galileo, the experience attended to the invisible processes of transformation that sustain all living things: what seems still continues to move.\n\nThe table became both territory and material landscape. Ceramic works, stones, metals and actual fragments from the studio coexisted with a plant-based menu whose forms blurred the edible and the rocky: bread like stones, lunar bites, foams, mushrooms and a volcanic dessert. Ceramics thus extended its research beyond the object, activated through touch, food and collective conversation.",
    "materials": "cerámica, metal, piedra, cristal, elementos de taller y alimentos vegetales",
    "techniques": "instalación, diseño de experiencia, puesta en escena y cena performativa",
    "dimensions": "instalación de mesa, dimensiones variables",
    "imageCount": 3,
    "number": 13
  },
  {
    "slug": "todo-lo-profundo-ama-el-disfraz",
    "category": "Exposiciones individuales",
    "titleEs": "Todo lo profundo ama el disfraz",
    "titleEn": "Everything Profound Loves a Mask",
    "period": "abril de 2023",
    "year": 2023,
    "status": "terminado",
    "type": "exposición individual",
    "place": "Madrid",
    "exhibition": "Todo lo profundo ama el disfraz",
    "institution": "Le Bâtiment",
    "curator": "PENDIENTE",
    "collaborators": "PENDIENTE",
    "introEs": "Cerámica y pintura construyen un espacio de camuflaje en el que lo íntimo aparece mediante formas que oscilan entre organismo, paisaje y personaje.",
    "introEn": "Ceramics and painting create a space of camouflage in which the intimate emerges through forms that shift between organism, landscape and character.",
    "bodyEs": "Todo lo profundo ama el disfraz* explora el camuflaje como estrategia de aparición y supervivencia. La exposición reúne cerámicas y pinturas en las que el ser y la naturaleza forman parte de un mismo tejido: cuerpos que se ocultan para revelarse, superficies que imitan pieles, minerales o vegetación y personajes que parecen surgir de un imaginario interior.\n\nEl proyecto entiende la creación como un territorio de juego, investigación y refugio. En obras como *Camuflaje*, *Camulabro*, *Maremagmun* e *Il cuore*, la materia se transforma en máscara sin quedar fijada a una identidad única. Lo profundo no se ofrece de manera directa; aparece desplazado en texturas, gestos y formas híbridas que mantienen abierta la tensión entre lo visible y lo oculto.",
    "bodyEn": "Everything Profound Loves a Mask* explores camouflage as a strategy of appearance and survival. The exhibition brings together ceramics and paintings in which being and nature belong to the same fabric: bodies that hide in order to reveal themselves, surfaces that resemble skin, minerals or vegetation, and characters that seem to emerge from an inner imaginary.\n\nThe project understands creation as a territory for play, research and refuge. In works such as *Camouflage*, *Camulabro*, *Maremagmun* and *Il cuore*, matter becomes a mask without being fixed to a single identity. The profound is not offered directly; it appears displaced into textures, gestures and hybrid forms that keep the tension between the visible and the concealed open.",
    "materials": "cerámica, esmaltes, pintura y técnica mixta",
    "techniques": "modelado cerámico, cocción, pintura e instalación",
    "dimensions": "variables",
    "imageCount": 3,
    "number": 14
  },
  {
    "slug": "viesca-de-reflexion",
    "category": "Exposiciones colectivas",
    "titleEs": "Viesca de reflexión",
    "titleEn": "A Grove for Reflection",
    "period": "22-23 de julio y 2 de septiembre-14 de octubre de 2023",
    "year": 2023,
    "status": "terminado",
    "type": "exposición colectiva / intervención en paisaje",
    "place": "bosque de hayas de Tierra del Agua, Caleao, Asturias; Galería Solaina, Lugo",
    "exhibition": "Viesca de reflexión",
    "institution": "Cerúleo y Galería Solaina",
    "curator": "Cerúleo",
    "collaborators": "Tierra del Agua, Galería Solaina y artistas participantes",
    "introEs": "Bailar hasta derretirme* trasladó al bosque una instalación pictórica y cerámica sobre el deseo de fundirse con un paisaje vivo y cambiante.",
    "introEn": "Dance Until I Melt* brought a painting and ceramic installation into the forest, exploring the desire to merge with a living, changing landscape.",
    "bodyEs": "Viesca de reflexión* invitó a recuperar la conexión con la naturaleza mediante una exposición situada primero en el hayedo de Tierra del Agua y trasladada después a la Galería Solaina. La propuesta atendía a la resiliencia del bosque, a sus recursos y a los saberes que permiten pensar otras relaciones con el entorno.\n\nLa participación de Brenda Ranieri, *Bailar hasta derretirme*, reunió una pintura sobre lino, un mural cerámico de cuatro piezas y una escultura. La instalación nace del deseo de prolongar una vivencia dentro de la naturaleza y disolver los límites entre cuerpo y paisaje. La pintura combina pigmentos naturales, óleo, spray y pastel; el mural registra durante un mes los movimientos de una planta; la escultura remite a un tronco, un torso y un refugio interior. Presentadas primero en el bosque y después en la galería, las piezas investigan cómo el contexto y la intemperie modifican su percepción.",
    "bodyEn": "A Grove for Reflection* invited visitors to recover their connection with nature through an exhibition first situated in the beech forest at Tierra del Agua and later transferred to Galería Solaina. The project attended to the forest's resilience, its resources and the knowledge through which other relationships with the environment can be imagined.\n\nBrenda Ranieri's contribution, *Dance Until I Melt*, brought together a painting on linen, a four-part ceramic mural and a sculpture. The installation grows from the desire to prolong an experience within nature and dissolve the boundaries between body and landscape. The painting combines natural pigments, oil, spray paint and pastel; the mural records a plant's movements over one month; and the sculpture evokes a trunk, a torso and an inner refuge. Shown first in the forest and later in the gallery, the works examine how context and exposure alter perception.",
    "materials": "lino, pigmentos naturales, óleo, spray, pastel, pasta refractaria, óxidos y esmaltes",
    "techniques": "pintura, teñido, modelado cerámico, observación y registro, instalación en paisaje",
    "dimensions": "pintura 116 × 81 cm; mural, cuatro piezas de 25 × 15 cm; escultura 22 × 53 cm",
    "imageCount": 3,
    "number": 15
  }
] as const;

export type Project = (typeof projects)[number];

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
