"""Add English counterparts for Spanish editorial overrides."""

from pathlib import Path


PATH = Path(__file__).resolve().parents[1] / "lib/projects.ts"


def replace_once(text: str, old: str, new: str) -> str:
    if text.count(old) != 1:
        raise RuntimeError(f"Expected one occurrence, found {text.count(old)}")
    return text.replace(old, new)


def main() -> None:
    text = PATH.read_text()
    replacements = [
        (
            '    introEs: "Esta instalación reúne una serie de vasijas conectadas por un sistema de agua que circula entre ellas y activa el hueco como espacio de resonancia.",',
            '    introEs: "Esta instalación reúne una serie de vasijas conectadas por un sistema de agua que circula entre ellas y activa el hueco como espacio de resonancia.",\n    introEn: "This installation brings together a series of vessels connected by a circulating water system that activates the hollow as a space of resonance.",',
        ),
        (
            '    bodyEs: "*Me tocó por dentro* reúne una serie de vasijas conectadas por un sistema de agua que circula entre ellas, donde el agua activa el hueco como espacio de resonancia. El título toma la expresión ruandesa *Yankoze Munda* —«me tocó por dentro»—, vinculada a un ritual femenino de acompañamiento y sanación comunitaria en el que el agua cae desde bolsas perforadas sobre la cabeza de quien atraviesa un proceso de transformación.\\n\\nLa obra retoma esta estructura simbólica: aquello que nos conmueve no permanece aislado, sino que circula y se transforma en comunidad. El gesto es mínimo, repetitivo y persistente. Cada vasija, realizada con técnicas mixtas y materiales recolectados como el metal, contiene y se deja afectar; el agua entra, insiste, gotea y produce una vibración casi imperceptible.",',
            '    bodyEs: "*Me tocó por dentro* reúne una serie de vasijas conectadas por un sistema de agua que circula entre ellas, donde el agua activa el hueco como espacio de resonancia. El título toma la expresión ruandesa *Yankoze Munda* —«me tocó por dentro»—, vinculada a un ritual femenino de acompañamiento y sanación comunitaria en el que el agua cae desde bolsas perforadas sobre la cabeza de quien atraviesa un proceso de transformación.\\n\\nLa obra retoma esta estructura simbólica: aquello que nos conmueve no permanece aislado, sino que circula y se transforma en comunidad. El gesto es mínimo, repetitivo y persistente. Cada vasija, realizada con técnicas mixtas y materiales recolectados como el metal, contiene y se deja afectar; el agua entra, insiste, gotea y produce una vibración casi imperceptible.",\n    bodyEn: "*It Touched Me Inside* brings together a series of vessels connected by a circulating water system, in which water activates the hollow as a space of resonance. The title draws on the Rwandan expression *Yankoze Munda*—‘it touched me inside’—linked to a women’s ritual of communal care and healing in which water falls from perforated bags onto the head of a person undergoing transformation.\\n\\nThe work takes up this symbolic structure: what moves us does not remain isolated, but circulates and is transformed in community. The gesture is minimal, repetitive and persistent. Each vessel, made through mixed techniques with gathered materials such as metal, both contains and allows itself to be affected; water enters, persists, drips and produces an almost imperceptible vibration.",',
        ),
        (
            '    introEs: "Brenda Ranieri presentó *Lo atamos con alambre* y *Antes del rayo* en la exposición colectiva *Cosas que cargan cosas*.",',
            '    introEs: "Brenda Ranieri presentó *Lo atamos con alambre* y *Antes del rayo* en la exposición colectiva *Cosas que cargan cosas*.",\n    introEn: "Brenda Ranieri presented *Lo atamos con alambre* and *Antes del rayo* in the group exhibition *Cosas que cargan cosas*.",',
        ),
        (
            '    introEs: "Fuentes cerámicas, agua y ruinas componen una hidrografía de ritmos lentos en los patios de la Galería Lapislázuli.",',
            '    introEs: "Fuentes cerámicas, agua y ruinas componen una hidrografía de ritmos lentos en los patios de la Galería Lapislázuli.",\n    introEn: "Ceramic fountains, water and ruins compose a hydrography of slow rhythms across the courtyards of Galería Lapislázuli.",',
        ),
        (
            '    bodyEs: "*La forma del agua quieta* parte de la relación entre jardín, fuente y cerámica como dispositivos para contener y dar cuerpo a materias inestables. Vasijas realizadas con arcillas locales y rocas recolectadas en el territorio conforman una serie de instalaciones de agua que intervienen los patios de la galería.\\n\\nLa propuesta nace de una contradicción: aquello que percibimos como inmóvil está atravesado por procesos continuos de transformación. El agua nunca permanece quieta; sedimenta, evapora, erosiona y circula incluso cuando parece detenida. Frente a la imagen apaciguada del jardín ornamental, la exposición revela ritmos lentos y casi imperceptibles, compartidos por el agua y la práctica cerámica.\\n\\nLas ruinas y las piezas dialogan simbióticamente con los árboles de los patios: los contienen, bordean o señalan y, al mismo tiempo, construyen con ellos una relación estética. Arcilla, piedra, porcelana, metal y esmalte conservan las marcas del fuego y del territorio, mientras el agua reactiva las obras y las mantiene abiertas al tiempo.",',
            '    bodyEs: "*La forma del agua quieta* parte de la relación entre jardín, fuente y cerámica como dispositivos para contener y dar cuerpo a materias inestables. Vasijas realizadas con arcillas locales y rocas recolectadas en el territorio conforman una serie de instalaciones de agua que intervienen los patios de la galería.\\n\\nLa propuesta nace de una contradicción: aquello que percibimos como inmóvil está atravesado por procesos continuos de transformación. El agua nunca permanece quieta; sedimenta, evapora, erosiona y circula incluso cuando parece detenida. Frente a la imagen apaciguada del jardín ornamental, la exposición revela ritmos lentos y casi imperceptibles, compartidos por el agua y la práctica cerámica.\\n\\nLas ruinas y las piezas dialogan simbióticamente con los árboles de los patios: los contienen, bordean o señalan y, al mismo tiempo, construyen con ellos una relación estética. Arcilla, piedra, porcelana, metal y esmalte conservan las marcas del fuego y del territorio, mientras el agua reactiva las obras y las mantiene abiertas al tiempo.",\n    bodyEn: "*The Shape of Still Water* begins with the relationship between garden, fountain and ceramics as devices for containing and giving form to unstable matter. Vessels made from local clays and stones gathered in the territory form a series of water installations across the gallery courtyards.\\n\\nThe proposal emerges from a contradiction: what we perceive as still is traversed by continuous processes of transformation. Water never remains still; it sediments, evaporates, erodes and circulates even when it appears motionless. Against the pacified image of the ornamental garden, the exhibition reveals slow, nearly imperceptible rhythms shared by water and ceramic practice.\\n\\nThe ruins and pieces enter into a symbiotic dialogue with the courtyard trees: they contain, border or point to them while building an aesthetic relationship with them. Clay, stone, porcelain, metal and glaze retain the marks of fire and territory, while water reactivates the works and keeps them open to time.",',
        ),
        (
            '    introEs: "Una investigación material en torno al botijo reúne tradición, reconstrucción y formas contemporáneas de inteligencia material.",',
            '    introEs: "Una investigación material en torno al botijo reúne tradición, reconstrucción y formas contemporáneas de inteligencia material.",\n    introEn: "A material investigation around the botijo brings together tradition, reconstruction and contemporary forms of material intelligence.",',
        ),
        (
            '    bodyEs: "La investigación entendió el estudio como un espacio de observación donde la materia conserva y revela información. Al incorporar café a mezclas de distintos solidificantes con arcilla silvestre, el proyecto atendió a sus transformaciones durante el secado lento y a la co-creación con materiales vivos.\\n\\nLas piezas no están cocidas: son resultados sólidos de una investigación todavía abierta. La práctica desafía así lo perenne y ensaya un campo donde control e incertidumbre, materia geológica y residuo orgánico negocian una forma común.",',
            '    bodyEs: "La investigación entendió el estudio como un espacio de observación donde la materia conserva y revela información. Al incorporar café a mezclas de distintos solidificantes con arcilla silvestre, el proyecto atendió a sus transformaciones durante el secado lento y a la co-creación con materiales vivos.\\n\\nLas piezas no están cocidas: son resultados sólidos de una investigación todavía abierta. La práctica desafía así lo perenne y ensaya un campo donde control e incertidumbre, materia geológica y residuo orgánico negocian una forma común.",\n    bodyEn: "The research approached the studio as a space of observation in which matter preserves and reveals information. By incorporating coffee into mixtures of different binders and wild clay, the project followed their transformations through slow drying and co-creation with living materials.\\n\\nThe pieces are unfired: they are solid outcomes of an investigation that remains open. The practice thus challenges permanence and tests a field in which control and uncertainty, geological matter and organic residue negotiate a shared form.",',
        ),
        (
            '    introEs: "Un espacio de conversación y experimentación colectiva en torno al agua, la memoria territorial y la arcilla local.",',
            '    introEs: "Un espacio de conversación y experimentación colectiva en torno al agua, la memoria territorial y la arcilla local.",\n    introEn: "A space for conversation and collective experimentation around water, territorial memory and local clay.",',
        ),
        (
            '    introEs: "Una ensoñación es un susurro interno: una vibración sutil que une los cuerpos, los modela, los forja y los contiene.",',
            '    introEs: "Una ensoñación es un susurro interno: una vibración sutil que une los cuerpos, los modela, los forja y los contiene.",\n    introEn: "A reverie is an inner whisper: a subtle vibration that joins bodies, shapes them, forges them and holds them.",',
        ),
        (
            '    bodyEs: "Una ensoñación es un susurro interno. Una vibración sutil que une los cuerpos, los modela, los forja y los contiene.\\n\\nTambién es un jardín latente, el murmullo del agua y de los seres que lo habitan. Muchos de estos jardines emanan de una ruina, constituyéndose en la mirada consciente y profunda, aquella que solo una ensoñación puede otorgar. De todo esto habla Brenda Ranieri en su diálogo íntimo con lo matérico, transitando el umbral donde lo tangible se disuelve y lo invisible se revela.\\n\\nTexto por Alejandra Díaz-Guerra.",',
            '    bodyEs: "Una ensoñación es un susurro interno. Una vibración sutil que une los cuerpos, los modela, los forja y los contiene.\\n\\nTambién es un jardín latente, el murmullo del agua y de los seres que lo habitan. Muchos de estos jardines emanan de una ruina, constituyéndose en la mirada consciente y profunda, aquella que solo una ensoñación puede otorgar. De todo esto habla Brenda Ranieri en su diálogo íntimo con lo matérico, transitando el umbral donde lo tangible se disuelve y lo invisible se revela.\\n\\nTexto por Alejandra Díaz-Guerra.",\n    bodyEn: "A reverie is an inner whisper. A subtle vibration that joins bodies, shapes them, forges them and holds them.\\n\\nIt is also a latent garden: the murmur of water and of the beings that inhabit it. Many of these gardens emanate from a ruin, becoming a conscious and profound gaze—the kind only a reverie can grant. Brenda Ranieri’s intimate dialogue with matter speaks of all this, crossing the threshold where the tangible dissolves and the invisible is revealed.\\n\\nText by Alejandra Díaz-Guerra.",',
        ),
        (
            '    bodyEs: "Entre lo lunar y lo terrestre, *Sin embargo, se mueve* propuso un gesto de comunión entre materia, cuerpo y entorno. Inspirada en la frase atribuida a Galileo, la experiencia atendía a los procesos invisibles de transformación que sostienen todo lo vivo: aquello que parece quieto continúa moviéndose.\\n\\nEn colaboración con el chef Brian González, la mesa se convirtió en territorio y paisaje material. Piezas cerámicas, piedras, metales y fragmentos reales del taller convivieron con un menú vegetal cuyas formas confundían lo comestible con lo rocoso. La cerámica extendió así su investigación más allá del objeto, activándose mediante el tacto, la comida y la conversación colectiva.",',
            '    bodyEs: "Entre lo lunar y lo terrestre, *Sin embargo, se mueve* propuso un gesto de comunión entre materia, cuerpo y entorno. Inspirada en la frase atribuida a Galileo, la experiencia atendía a los procesos invisibles de transformación que sostienen todo lo vivo: aquello que parece quieto continúa moviéndose.\\n\\nEn colaboración con el chef Brian González, la mesa se convirtió en territorio y paisaje material. Piezas cerámicas, piedras, metales y fragmentos reales del taller convivieron con un menú vegetal cuyas formas confundían lo comestible con lo rocoso. La cerámica extendió así su investigación más allá del objeto, activándose mediante el tacto, la comida y la conversación colectiva.",\n    bodyEn: "Between the lunar and the terrestrial, *And Yet, It Moves* proposed a gesture of communion between matter, body and environment. Inspired by the phrase attributed to Galileo, the experience attended to the invisible processes of transformation that sustain all living things: what appears still continues to move.\\n\\nIn collaboration with chef Brian González, the table became territory and material landscape. Ceramic pieces, stones, metals and actual fragments from the studio coexisted with a plant-based menu whose forms blurred the edible and the rocky. Ceramics extended its research beyond the object, activated through touch, food and collective conversation.",',
        ),
    ]
    for old, new in replacements:
        text = replace_once(text, old, new)
    PATH.write_text(text)


if __name__ == "__main__":
    main()
