"""Localize the OAX archive headings and explanatory copy."""
from pathlib import Path

p = Path(__file__).resolve().parents[1] / "app/components/oax-project-blocks.tsx"
s = p.read_text()
s = s.replace('export function OaxProjectBlocks({ project, images, rayograms, fieldArchive }: { project: ProjectRecord; images: OaxImage[]; rayograms: OaxImage[]; fieldArchive: OaxImage[] }) {\n  const paragraphs = project.bodyEs', 'export function OaxProjectBlocks({ project, images, rayograms, fieldArchive, language = "es" }: { project: ProjectRecord; images: OaxImage[]; rayograms: OaxImage[]; fieldArchive: OaxImage[]; language?: "es" | "en" }) {\n  const isEs = language === "es";\n  const paragraphs = (isEs ? project.bodyEs : project.bodyEn)')
s = s.replace('<a href="#oax-project"><span>01</span><strong>El proyecto</strong><small>Open Studio · marzo 2026</small></a>', '<a href="#oax-project"><span>01</span><strong>{isEs ? "El proyecto" : "The project"}</strong><small>Open Studio · {isEs ? "marzo" : "March"} 2026</small></a>')
s = s.replace('<a href="#oax-situated-archive"><span>02</span><strong>Archivo investigación material de Carabanchel</strong><small>Registros del proceso en 35 mm</small></a>', '<a href="#oax-situated-archive"><span>02</span><strong>{isEs ? "Archivo de investigación material de Carabanchel" : "Carabanchel material research archive"}</strong><small>{isEs ? "Registros del proceso en 35 mm" : "35 mm process records"}</small></a>')
s = s.replace('<a href="#oax-rayograms"><span>03</span><strong>Archivo rayogramas de agua</strong><small>Procesos de co-creación</small></a>', '<a href="#oax-rayograms"><span>03</span><strong>{isEs ? "Archivo rayogramas de agua" : "Water rayogram archive"}</strong><small>{isEs ? "Procesos de co-creación" : "Co-creation processes"}</small></a>')
s = s.replace('<h2 id="oax-project-title">El proyecto</h2>', '<h2 id="oax-project-title">{isEs ? "El proyecto" : "The project"}</h2>')
s = s.replace('<article className="oax-inline-copy"><span>Contexto y proceso</span>', '<article className="oax-inline-copy"><span>{isEs ? "Contexto y proceso" : "Context and process"}</span>')
s = s.replace('<h2 id="oax-archive-title">Archivo investigación material de Carabanchel</h2><div><p>Fotografías analógicas de 35 mm tomadas durante el desarrollo del proyecto. El archivo reúne escenas de producción en el taller, pruebas sistemáticas con materiales recolectados del paisaje urbano, visitas a los talleres del barrio para recuperar materia y registros de la preparación de la cocción a leña de algunas de las piezas.</p></div>', '<h2 id="oax-archive-title">{isEs ? "Archivo de investigación material de Carabanchel" : "Carabanchel material research archive"}</h2><div><p>{isEs ? "Fotografías analógicas de 35 mm tomadas durante el desarrollo del proyecto. El archivo reúne escenas de producción en el taller, pruebas sistemáticas con materiales recolectados del paisaje urbano, visitas a los talleres del barrio para recuperar materia y registros de la preparación de la cocción a leña de algunas de las piezas." : "35 mm analogue photographs taken during the development of the project. The archive brings together studio production, systematic tests with materials gathered from the urban landscape, visits to neighbourhood workshops to recover matter, and records of preparations for the wood firing of several pieces."}</p></div>')
s = s.replace('<h2 id="oax-ray-title">Archivo rayogramas de agua</h2><div><p>El agua resultante de la decantación de arcilla de Carabanchel, recolectada en un espacio en obra, se trasladó al laboratorio para producir fotografías sin cámara junto a la artista Ana Paes. Las imágenes fueron montadas sobre papel con la ayuda de la grabadora Paula Cid Cerezo y su tórculo.</p></div>', '<h2 id="oax-ray-title">{isEs ? "Archivo rayogramas de agua" : "Water rayogram archive"}</h2><div><p>{isEs ? "El agua resultante de la decantación de arcilla de Carabanchel, recolectada en un espacio en obra, se trasladó al laboratorio para producir fotografías sin cámara junto a la artista Ana Paes. Las imágenes fueron montadas sobre papel con la ayuda de la grabadora Paula Cid Cerezo y su tórculo." : "Water from the settling of Carabanchel clay, gathered at a construction site, was taken to the laboratory to produce cameraless photographs with artist Ana Paes. The images were mounted on paper with printmaker Paula Cid Cerezo and her etching press."}</p></div>')
p.write_text(s)
print("Localized OAX")
